movielibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies_app.urls')),
]

movies_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name="about"),
    path('movies/', views.MovieList.as_view(), name="index"),
    path('movies/<int:movie_id>/', views.movies_detail, name='detail'),
    path('movies/create/', views.MovieCreate.as_view(), name='movies_create'),
    path('movies/<int:pk>/update/', views.MovieUpdate.as_view(), name='movies_update'),
    path('movies/<int:pk>/delete/', views.MovieDelete.as_view(), name='movies_delete'),
    path('movies/<int:movie_id>/add_award/', views.add_award, name='add_award'),
    path('performers/', views.PerformerList.as_view(), name='performer_index'),
    path('performers/<int:pk>/', views.PerformerDetail.as_view(), name='performer_detail'),
    path('performers/create/', views.PerformerCreate.as_view(), name='performer_create'),
    path('performers/<int:pk>/update/', views.PerformerUpdate.as_view(), name='performer_update'),
    path('performers/<int:pk>/delete/', views.PerformerDelete.as_view(), name='performer_delete'),
    path('movies/<int:movie_id>/assoc_cast/<int:performer_id>/', views.assoc_cast, name='assoc_cast'),
]

movies_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
AWARDS = (
    ('O', 'Oscar'),
    ('A', "Academy Award"),
    ('S', 'Screen Actors Guild'),
)

class Performer(models.Model):
    first = models.CharField(max_length=100)
    last = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first} {self.last}"

    def get_absolute_url(self):
        return reverse('performer_detail', kwargs={'pk': self.id})

class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_year = models.IntegerField()
    director = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    cast = models.ManyToManyField(Performer)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'movie_id': self.id})

    def is_popular(self):
        return self.award_set.all().count() > 2

class Award(models.Model):
    year = models.IntegerField()
    category = models.CharField(max_length=100)
    name = models.CharField(
        max_length=1,
        choices=AWARDS,
        default=AWARDS[0][0]
    )

    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_award_display()} on {self.date}"
    
    class Meta:
        ordering = ['-year']

movies_app/forms.py
from django.forms import ModelForm
from .models import Award

class AwardForm(ModelForm):
    class Meta:
        model = Award
        fields = ['year', 'name', 'category']

movies_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Movie, Performer
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .forms import AwardForm


class MovieList(ListView):
    model = Movie
    template_name = 'movies/index.html'

class MovieCreate(CreateView):
    model = Movie
    fields = '__all__'

class MovieUpdate(UpdateView):
    model = Movie
    fields = ['release_year', 'director', 'genre']

class MovieDelete(DeleteView):
    model = Movie
    success_url = '/movies/'

def home(request):
    return HttpResponse('<h1>Hello</h1>')

def about(request):
    return render(request, 'about.html')

# def movies_index(request):
#     movies = Movie.objects.all()
#     return render(request, 'movies/index.html', {'movies': movies})

def movies_detail(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    cast_movie_doesnt_have = Performer.objects.exclude(id__in = movie.cast.all().values_list('id'))
    award_form = AwardForm()
    return render(request, 'movies/detail.html', {
        'movie': movie,
        'award_form': award_form,
        'cast': cast_movie_doesnt_have 
    })

def add_award(request, movie_id):
    form = AwardForm(request.POST)
    if form.is_valid():
        new_award = form.save(commit=False)
        new_award.movie_id = movie_id
        new_award.save()
    return redirect('detail', movie_id=movie_id)

def assoc_cast(request, movie_id, performer_id):
    Movie.objects.get(pk=movie_id).cast.add(performer_id)
    return redirect('detail', movie_id=movie_id)

class PerformerList(ListView):
  model = Performer

class PerformerDetail(DetailView):
  model = Performer

class PerformerCreate(CreateView):
  model = Performer
  fields = '__all__'

class PerformerUpdate(UpdateView):
  model = Performer
  fields = '__all__'

class PerformerDelete(DeleteView):
  model = Performer
  success_url = '/performers/'

movies_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Movie Library</h1>
<hr />
<p>Coming soon!</p>

{% endblock %}

movies_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Movie Library</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;MovieLibrary</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'performer_create' %}">Add a Performer</a></li>
          <li><a href="{% url 'performer_index' %}">View All Performers</a></li>
          <li><a href="{% url 'movies_create' %}">Add a Movie</a></li>
          <li><a href="{% url 'index' %}">View All Movies</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Movie Library &nbsp;</div>
  </footer>
</body>
</html>

movies_app/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Movie Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
            <span class="card-title">{{ movie.title }}</span>
            <p>Director: {{ movie.director }}</p>
            <p>Release: {{ movie.release_year }}</p>
            <p>Genre: {{ movie.genre }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'movies_update' movie.id %}">Edit</a>
                <a href="{% url 'movies_delete' movie.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_award' movie.id %}" method="post">
            {% csrf_token %}
            {{ award_form.as_p }}
            <input type="submit" class="btn" value="Add Award">
        </form>
        {% if movie.is_popular %}
            <div class="card-panel teal-text center-align">{{movie.title}} is a popular film!</div>
        {% else %}
            <div class="card-panel red-text center-align">{{movie.title}} may have been a rotten tomato.</div>
        {% endif %}
        <table class="striped">
            <thead>
            <tr><th>Year</th><th>Name</th><th>Category</th></tr>
            </thead>
            <tbody>
            {% for award in movie.award_set.all %}
                <tr>
                <td>{{award.year}}</td>
                <td>{{award.get_name_display}}</td>
                <td>{{award.category}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ movie.title }}'s Cast</h3>
    {% if movie.cast.count %}
      {% for performer in movie.cast.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
               {{ performer.first }} {{ performer.last }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Cast Provided :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Performers</h3>
    {% if cast.count %}
      {% for performer in cast.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
                {{ performer.first }} {{ performer.last }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_cast' movie.id performer.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{movie.title}} Has Cast all Available Performers</h5>
    {% endif %}
  </div>
<script>
    const selectEl = document.getElementById('id_name');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

movies_app/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Movie List</h1>

{% for movie in movie_list %}
  <div class="card">
    <a href="{% url 'detail' movie.id %}">
    <div class="card-content">
      <span class="card-title">{{ movie.title }}</span>
      <p>Director: {{ movie.director }}</p>
      <p>Release: {{ movie.release_year }}</p>
      <p>Genre: {{ movie.genre }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

movies_app/templates/movies_app/movie_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Movie</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' movie.id %}">Cancel</a>
  </form>
{% endblock %}

movies_app/templates/movies_app/movie_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.title}}</span></h1>
  {% else %}
    <h1>Add Movie</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

movies_app/templates/movies_app/performer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Remove Performer</h1>

  <h4>Are you sure you want to remove <span class="teal-text">{{ object.first }} {{ object.last }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'performer_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

movies_app/templates/movies_app/performer_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Performer Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ performer.first }} {{ performer.last }}</span>
        <p>Talented Performer</p>
      </div>
      <div class="card-action">
        <a href="{% url 'performer_update' performer.id %}">Edit</a>
        <a href="{% url 'performer_delete' performer.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

movies_app/templates/movies_app/performer_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{performer.first}} {{performer.last}}</span></h1>
  {% else %}
    <h1>Add performer</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

movies_app/templates/movies_app/performer_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Performer List</h1>

{% for performer in performer_list %}
  <a href="{% url 'performer_detail' performer.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ performer.first }} {{ performer.last }}</span>
            <p>Talented Performer</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}